#!/usr/bin/env bash

make lint

# $? stores exit value of the last command
if [ $? -ne 0 ]; then
    echo -e "\e[0m\e[1m\e[31m\e[5m"
    echo -e "🚨 \e[5m Your code is not acceptable \e[25m🚨"
    echo -e "\e[0m\e[1m\e[33m"
    echo "You have to fix your code in order to commit."
    echo -e "\e[0m"
    exit 1
fi

make build

# $? stores exit value of the last command
if [ $? -ne 0 ]; then
    echo -e "\e[0m\e[1m\e[31m\e[5m"
    echo -e "🚨 \e[5m Build failed \e[25m🚨"
    echo -e "\e[0m\e[1m\e[33m"
    echo "You have to fix your code in order to commit."
    echo -e "\e[0m"
    exit 1
fi