# This is a basic workflow to help you get started with Actions

name: test

env:
  NODE_VERSION: 12

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # watch:
  #     types: [started] # trigger when star button is pressed (for debug purpose)
  push:
    branches: [master]
    # paths: [.github/workflows/**, src/**, test/**, package.json]
  pull_request:
    branches: [master]
  #schedule:
  #  - cron:  '0 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # prevent run when pull request occurred to disallow double launch
    if: (github.event_name == 'pull_request' || contains(toJSON(github.event.head_commit.message), 'Merge pull request ') == false)

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      # Setup node by optionally downloading and caching it
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Setup npm to be able to download from and publish to a custom registry
      - name: Setup npm
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          npm config set "@webcomponent:registry" "https://npm.cloudsmith.io/elency/webcomponents/"
          npm config set "//npm.cloudsmith.io/elency/webcomponents/:_authToken" "$CLOUDSMITH_API_KEY"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Setup cross browser testing
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm ci

      - run: make lint

      - run: make build

      - name: test end to end
        run: INDENT=true node ./build/test/end2end/test/end2end/*.spec.js | npx tap-mocha-reporter spec
